"""empty message

Revision ID: a37f21645ba2
Revises: 01cab35afb8b
Create Date: 2020-05-28 01:30:51.617243

"""
from alembic import op
import sqlalchemy as sa
import json

from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker

import models

# revision identifiers, used by Alembic.
revision = 'a37f21645ba2'
down_revision = '01cab35afb8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
